"""empty message

Revision ID: 7896c9033459
Revises: 
Create Date: 2024-03-27 15:19:20.046448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7896c9033459'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daugia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dotgd', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('stt', sa.Integer(), nullable=False))
        batch_op.drop_column('idndg')
        batch_op.drop_column('pricedg')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('picprd')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('fullname',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('hopthu',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('hopthu',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=25),
               nullable=True)
        batch_op.alter_column('fullname',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picprd', sa.TEXT(), nullable=False))

    with op.batch_alter_table('daugia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricedg', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('idndg', sa.INTEGER(), nullable=False))
        batch_op.drop_column('stt')
        batch_op.drop_column('dotgd')

    # ### end Alembic commands ###
